version: "3.7"

services:
  colax-worker-python:
    image: colax-worker-python:latest
    build: .
    networks:
      - colax-python
    environment:
      COLAX_CONSUL_ADDR: "consul-client:8500"
      COLAX_WORKER_HOST: "colax-worker-python"
    ports:
      - "6743:8000"
    volumes:
      - ${HOME}/.colax/volumes/worker/python/problems:/problems

networks:
  colax-python:
    name: colax-server
    external: true
